### ISSUE TITLE
Getting error while running inference code

### ISSUE THREAD

**Issue by mitdave95** [upfusion3d/upfusion#1]
Hi, getting the below error while running inference code

python -m scripts.run_distillation \
	--in_dir ./examples/lock \
	--out_dir /path/to/output_dir \
	--weights_dir /path/to/weights \
	--name lock
	
```
Traceback (most recent call last):
  File "/home/mit/anaconda3/envs/upfusion/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mit/anaconda3/envs/upfusion/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/d/Git/upfusion/scripts/run_distillation.py", line 17, in <module>
    from pytorch3d.renderer import PerspectiveCameras
  File "/home/mit/anaconda3/envs/upfusion/lib/python3.10/site-packages/pytorch3d/renderer/__init__.py", line 7, in <module>
    from .blending import (
  File "/home/mit/anaconda3/envs/upfusion/lib/python3.10/site-packages/pytorch3d/renderer/blending.py", line 10, in <module>
    from pytorch3d import _C
ImportError: /home/mit/anaconda3/envs/upfusion/lib/python3.10/site-packages/pytorch3d/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106SymInt19promote_to_negativeEv
```
	

on wsl ubuntu, rtx 4090 with cuda 11.7

**Comment by thatbrguy** [comment]
It should most likely be an issue with installing pytorch3d. I personally did not face this issue with the current installation script.

Could you try uninstalling and reinstalling pytorch3d? Do let me know if the issue still persists, thanks!

**Comment by mitdave95** [comment]
It worked. Uninstalled cuda and pytorch3d and reinstalled it.
